13-OS_CommandInjection/before/CommandInjection/Controllers/NslookupController.cs
using System.Diagnostics;
using System.Web.Mvc;

namespace CommandInjection.Controllers
{
    public class NslookupController : Controller
    {
        // GET: Nslookup
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(string tbxDomain)
        {
            string result = "";

            var proc = new Process
            {
                StartInfo = new ProcessStartInfo
                {
                    FileName = "cmd.exe",
                    Arguments = "/c nslookup " + tbxDomain,
                    UseShellExecute = false,
                    RedirectStandardOutput = true,
                    CreateNoWindow = true
                }
            };

            proc.Start();
            while (!proc.StandardOutput.EndOfStream)
            {
                string line = proc.StandardOutput.ReadLine();
                result += line + "<br />";
            }
            ViewData["result"] = result;
            return View();
        }
    }
}

13-OS_CommandInjection/before/CommandInjection/Views/Nslookup/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Index", "Nslookup", FormMethod.Post))
        {
            @Html.TextBox("tbxDomain", null, new { style = "width:300px" })
            <input type="submit" value="nslookup" />
        }
        <br />
        <span>@Html.Raw(@ViewData["result"])</span>
    </div>
</body>
</html>